
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/ 

server:
  port: 9000
  shutdown: graceful


spring:
  
  lifecycle:
    timeout-per-shutdown-phase: 15s
  
  cloud:
    
    gateway:
      httpclient:
        connect-timeout: 2000 # 2s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        # - SaveSession
        # - TokenRelay
        # - name: RequestRateLimiter
        #   args:
        #     redis-rate-limiter.replenishRate: 10
        #     redis-rate-limiter.burstCapacity: 20
        #     redis-rate-limiter.requestedTokens: 1
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        
        - id: catalog-route
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalog-fallback
        - id: order-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/catalog-fallback
  # redis:
  #   connect-timeout: 2s
  #   host: localhost
  #   port: 6379
  #   timeout: 1s
  # session:
  #   store-type: redis
  #   timeout: 10m
  #   redis:
  #     namespace: myapp:edge
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         keycloak:
  #           client-id: api-gateway-service
  #           client-secret: myapp-keycloak-secret
  #           scope: openid,roles
  #       provider:
  #         keycloak:
  #           issuer-uri: http://myapp-redis:8080/realms/ecomappProductshop

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
