spring:
  r2dbc:
    url: r2dbc:postgresql://catalofmsdb.cjwpwsb7y4xs.ap-south-1.rds.amazonaws.com:5432/catalog
    
    username: postgres
    password: admin1234
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

  
       
server:
  port: 9002 

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/        
        
      
